// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8XUEnYo-BdPHiW3K0IBTjUnXzyrWrITw',
    appId: '1:4703529935:web:738e6ac4694e09f31e00ba',
    messagingSenderId: '4703529935',
    projectId: 'auth-e85df',
    authDomain: 'auth-e85df.firebaseapp.com',
    storageBucket: 'auth-e85df.appspot.com',
    measurementId: 'G-PZMCV788KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHu_z81oQQe93qcrcX-3i--zQBznoLf94',
    appId: '1:329671345929:android:48927eae96849426ef75d8',
    messagingSenderId: '4703529935',
    projectId: 'calendar-app-a7283',
    storageBucket: 'calendar-app-a7283.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkbC3UBUkTIQ52clwj9hiFTTT9mimv8vQ',
    appId: '1:4703529935:ios:8874f37ec7dcf3971e00ba',
    messagingSenderId: '4703529935',
    projectId: 'auth-e85df',
    storageBucket: 'auth-e85df.appspot.com',
    iosBundleId: 'com.example.calendarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkbC3UBUkTIQ52clwj9hiFTTT9mimv8vQ',
    appId: '1:4703529935:ios:41473fd1f61e7f211e00ba',
    messagingSenderId: '4703529935',
    projectId: 'auth-e85df',
    storageBucket: 'auth-e85df.appspot.com',
    iosBundleId: 'com.example.calendarApp.RunnerTests',
  );
}
