// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHu_z81oQQe93qcrcX-3i--zQBznoLf94',
    appId: '1:329671345929:android:f77bc06ca3792685ef75d8',
    messagingSenderId: '329671345929',
    projectId: 'calendar-app-a7283',
    storageBucket: 'calendar-app-a7283.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlhT-0yXMGEXKJfULJl3U3Iu6u7paE0BE',
    appId: '1:329671345929:ios:41874caa5b58208bef75d8',
    messagingSenderId: '329671345929',
    projectId: 'calendar-app-a7283',
    storageBucket: 'calendar-app-a7283.appspot.com',
    androidClientId: '329671345929-5vciuiol5buvfo4bhe9ti64tph43biir.apps.googleusercontent.com',
    iosClientId: '329671345929-ms66cldgh0ih7p83fkg0cqgseldauei6.apps.googleusercontent.com',
    iosBundleId: 'com.rookeys.calendar',
  );
}
